node:
  big-bang:
    type: public
    genesis-id: b_9wVSMGScDVC99ZZBHVh16mB1o67ehMhuK8zAnSJRZHkn
    source-path: https://raw.githubusercontent.com/PlasmaLaboratories/plasma-genesis-testnets/main/devnet
